apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubevirt.github.io/kubevirt-helm/ 
    chart: kubevirt
    targetRevision: v1.0.0 
    helm:
      parameters:
        - name: kubevirt
          value: kubevirt
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
