apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: details
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: vmi-details
    app: details
    version: v1
  name: vmi-details
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: registrydisk
          volumeName: registryvolume
        - disk:
            bus: virtio
          name: cloudinitdisk
          volumeName: cloudinitvolume
      interfaces:
        - name: testSlirp
          slirp: {}
          ports:
            - name: http
              port: 9080
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
    - name: testSlirp
      pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
    - name: registryvolume
      registryDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
    - cloudInitNoCloud:
        userData: |-
          #!/bin/bash
          echo "fedora" |passwd fedora --stdin
          yum install git ruby -y
          git clone https://github.com/istio/istio.git
          cd istio/samples/bookinfo/src/details/
          ruby details.rb 9080 &
      name: cloudinitvolume
status: {}
---
..........