# apiVersion: networking.istio.io/v1
# kind: Sidecar
# metadata:
#   name: transfers
#   namespace: transfers
# spec:
#   workloadSelector:
#     labels:
#       app.kubernetes.io/instance: transfers 
#   egress:
#   - port:
#       number: 80
#       protocol: HTTP
#       name: egresshttp
#     hosts:
#     - "accounts/*"
#     # - "limits/*"    
#   - hosts:
#     - "istio-system/*"
