---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: transfers-dest-rule
  namespace: transfers
spec:
  host: transfers-ms-base.transfers.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 20s
      baseEjectionTime: 30s