apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: istio-system    
spec:
  vault:
    server: http://vault.vault.svc.cluster.local:8200
    path: pki_int_west/sign/istio-ca
    auth:
      kubernetes:
        mountPath: /v1/auth/west
        role: issuer
        secretRef:
          name: issuer-token-lmzpj
          key: token           