# kind-config.yaml.j2
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001  # NodePort you want to expose
        hostPort: 30001       # Host port to forward to
        protocol: TCP

      - containerPort: 30080  # NodePort you want to expose
        hostPort: 30080       # Host port to forward to
        protocol: TCP

      - containerPort: 30443  # NodePort you want to expose
        hostPort: 30443       # Host port to forward to
        protocol: TCP


