# kind-config.yaml.j2
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001  # NodePort you want to expose
        hostPort: 30001       # Host port to forward to
        protocol: TCP

      - containerPort: 31080 
        hostPort: 31080     
        protocol: TCP

      - containerPort: 31443  
        hostPort: 31443       
        protocol: TCP

    labels:
      topology.kubernetes.io/region: uae
      topology.kubernetes.io/zone: auh-zone  

  - role: worker
    labels:
      topology.kubernetes.io/region: uae
      topology.kubernetes.io/zone: auh-zone          


