
---
- name: Set vault_command variable
  set_fact:
    vault_command: "kubectl exec -n vault -it vault-0 -- vault"
    root_ca: "./east/root_ca.json"    
    certs_path: "/tmp/certs"
    root_pki_path: "pki_root"
    intermediate_pki_prefix: "pki_int"    
    vault_host: "http://vault.vault.svc.cluster.local:8200"

- name: Create Intermediate PKI engine for the given cluster
  command: >
    vault secrets enable -path={{ intermediate_pki_prefix }}_{{ inventory_hostname }} pki
    
- name: Set the max lease TTL for the Intermediate PKI engine
  command: >
    vault secrets tune -max-lease-ttl=43800h {{ intermediate_pki_prefix }}_{{ inventory_hostname }}

- name: Generate the Intermediate CA certificate signing request (CSR)
  command: >
    vault write -format=json {{ intermediate_pki_prefix }}_{{ inventory_hostname }}/intermediate/generate/internal
    common_name="mydomain.com intermediate {{ inventory_hostname }}"
  register: intermediate_csr

- name: Save the Intermediate CSR to file
  copy:
    content: "{{ intermediate_csr.json.data.csr }}"
    dest: "{{ certs_path }}/pki_intermediate_{{ inventory_hostname }}.csr"
    mode: "0644"

- name: Sign the Intermediate certificate using the Root CA
  command: >
    vault write -format=json {{ root_pki_path }}/root/sign-intermediate
    csr=@{{ certs_path }}/pki_intermediate_{{ inventory_hostname }}.csr
    format=pem ttl="43800h"
  register: signed_intermediate_cert

- name: Save the signed Intermediate certificate
  copy:
    content: "{{ signed_intermediate_cert.json.data.certificate }}"
    dest: "{{ certs_path }}/intermediate_{{ inventory_hostname }}.cert.pem"
    mode: "0644"


- name: Combine the Intermediate certificate and Root certificate into a chain
  command: >
    cat {{ certs_path }}/intermediate_{{ inventory_hostname }}.cert.pem {{ certs_path }}/CA_cert.crt
    > {{ certs_path }}/intermediate_{{ inventory_hostname }}.chain.pem
  delegate_to: localhost
- name: Upload the signed Intermediate certificate chain to Vault
  command: >
    vault write {{ intermediate_pki_prefix }}_{{ inventory_hostname }}/intermediate/set-signed
    certificate=@{{ certs_path }}/intermediate_{{ inventory_hostname }}.chain.pem


- name: Create a role in the Intermediate PKI engine for Istio
  command: >
    vault write {{ intermediate_pki_prefix }}_{{ inventory_hostname }}/roles/istio-ca-{{ inventory_hostname }}
    allowed_domains=istio-ca
    allow_any_name=true
    enforce_hostnames=false
    require_cn=false
    allowed_uri_sans="spiffe://*"
    max_ttl=72h