# kind-config.yaml.j2
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30002  # NodePort you want to expose
        hostPort: 30002       # Host port to forward to
        protocol: TCP

      - containerPort: 31080  # NodePort you want to expose
        hostPort: 31080       # Host port to forward to
        protocol: TCP

      - containerPort: 31443  # NodePort you want to expose
        hostPort: 31443       # Host port to forward to
        protocol: TCP
