# kind-config.yaml.j2
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30002 
        hostPort: 30002      
        protocol: TCP

      - containerPort: 32080 
        hostPort: 32080       
        protocol: TCP

      - containerPort: 32443  
        hostPort: 32443      
        protocol: TCP

    labels:
      topology.kubernetes.io/region: uae
      topology.kubernetes.io/zone: dxb-zone  

  - role: worker
    labels:
      topology.kubernetes.io/region: uae
      topology.kubernetes.io/zone: dxb-zone          
