---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: limits-dest-rule
  namespace: accounts
spec:
  host: limits-ms-base.limits.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 20s
      baseEjectionTime: 30s