---
- hosts: all
  become: true
  vars:

    vault_command_east: "kubectl exec -n vault -it vault-0 -- vault"
    vault_command_west: "vault"

  tasks:  
    - name: Install Docker and Dependencies
      include_tasks: tasks/docker.yml

    - name: Install Kind, kubectl and Create Kind Clusters
      include_tasks: tasks/kind.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Get kubeconfig
      include_tasks: tasks/kubeconfig.yml

    - name: Install and Configure ArgoCD
      include_tasks: tasks/argo.yml    

    - name: Install Helm and Manage Repositories
      include_tasks: tasks/helm.yml

    - name: Install Vault
      include_tasks: tasks/vault-install.yml    
      when: inventory_hostname == "east"     

    - name: Configure Vault
      include_tasks: tasks/vault-configure.yml        
 
    - name: Save Istio Remote Secret File
      include_tasks: tasks/remote-secret.yml        

    - name: Install cert-manager
      include_tasks: tasks/cert-manager.yml  

    - name: Install vault-issuer
      include_tasks: tasks/vault-issuer.yml      

    - name: Install cert-manager-istio-csr
      include_tasks: tasks/cert-manager-istio-csr.yml 

    - name: Setup Istio
      include_tasks: tasks/istio.yml
