Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 3
  end

  # Define east VM with public IP
  config.vm.define "east" do |east|
    east.vm.hostname = "east"
    east.vm.network "public_network", ip: "192.168.1.10"  
    
    east.vm.network "forwarded_port", guest: 32000, host: 32000
    east.vm.network "forwarded_port", guest: 31000, host: 31000    
    east.vm.network "forwarded_port", guest: 30080, host: 30080     
    east.vm.network "forwarded_port", guest: 30443, host: 30443           

    east.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"
      ansible.extra_vars = { 
        "inventory_hostname" => "east",
        "argo_node_port" => "32000",
        "istio_igw_http_port" => "30080",
        "istio_igw_https_port" => "30443",
        "istio_version" => "1.23.3",
        "istio_mesh_name" => "uaemesh"                
      }
    end
  end

  # # Define west VM with public IP
  config.vm.define "west" do |west|
    west.vm.hostname = "west"
    west.vm.network "public_network", ip: "192.168.1.11"


    west.vm.network "forwarded_port", guest: 32000, host: 32001  
    west.vm.network "forwarded_port", guest: 31000, host: 31001      
    west.vm.network "forwarded_port", guest: 30080, host: 31080     
    west.vm.network "forwarded_port", guest: 30443, host: 31443  
        

    west.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"
      ansible.extra_vars = { 
        "inventory_hostname" => "west",
        "argo_node_port" => "32000",
        "istio_igw_http_port" => "30080",
        "istio_igw_https_port" => "30443",
        "istio_version" => "1.23.3",
        "istio_mesh_name" => "uaemesh"                  
      }
    end
  end


end
