---
- name: Set variables
  set_fact:
    desired_version: "v0.12.0" 

- name: Add Helm repository for cert-manager-istio-csr
  command:
    cmd: helm repo add jetstack https://charts.jetstack.io
  register: helm_repo_add
  failed_when: "'Error' in helm_repo_add.stderr"
  changed_when: "'Error' not in helm_repo_add.stderr"
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"

- name: Update Helm repositories
  command:
    cmd: helm repo update
  register: helm_repo_update
  failed_when: "'Error' in helm_repo_update.stderr"
  changed_when: "'Error' not in helm_repo_update.stderr"
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"

- name: Check if cert-manager-istio-csr is already installed
  command: "helm status cert-manager-istio-csr -n cert-manager"
  register: helm_release_check
  failed_when: helm_release_check.rc not in [0, 1]
  changed_when: false
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"

- name: Install cert-manager-istio-csr using Helm and wait for it to become healthy
  command: >
    helm install cert-manager-istio-csr jetstack/cert-manager-istio-csr --namespace cert-manager \
    --version {{ desired_version }} \
    --set app.server.clusterID={{ cluster.name }} \
    --wait \
    --timeout 600s
  when: helm_release_check.rc != 0
  register: helm_install
  failed_when: helm_install.rc != 0
  changed_when: helm_install.rc == 0
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"

- name: Ensure cert-manager-istio-csr is deployed and healthy
  command:
    cmd: helm status cert-manager-istio-csr --namespace cert-manager
  register: helm_status
  retries: 10
  delay: 30
  until: "'STATUS: deployed' in helm_status.stdout"
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"
