- name: Set variables
  set_fact:    
    istio_version: "1.23.3"

- name: Check if istioctl is installed
  command: istioctl version --remote=false
  register: istioctl_check
  ignore_errors: true  # Allow the task to fail without interrupting the playbook
  changed_when: false

- name: Download and install istioctl with version
  shell: |
    curl -sL https://istio.io/downloadIstioctl | ISTIO_VERSION={{ istio_version }} sh -
  args:
    creates: "{{ ansible_env.HOME }}/.istioctl/bin/istioctl"
  when: istioctl_check.failed

- name: Verify istioctl installation
  command: istioctl version --remote=false
  register: istioctl_verify
  changed_when: false