
- name: Create cluster with kind
  shell: kind create cluster --name {{ cluster.name }}
  ignore_errors: true
  become: false

- name: Export kubeconfig for the cluster
  shell: kind get kubeconfig --name {{ cluster.name }} > {{ cluster.kubeconfig }}
  changed_when: false
  become: true

# - name: Set kubectl context for the cluster
#   command: kubectl config use-context kind-{{ cluster.name }}
#   become: false
