---

- name: Set variables
  set_fact:
    desired_version: "v0.17.0"

- name: Check if kind is installed
  command: kind --version
  register: kind_check
  ignore_errors: true

- name: Install specific version of kind if not installed
  block:
    - name: Download and install specific version of kind
      shell: |
        curl -Lo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/{{ desired_version }}/kind-darwin-amd64
        chmod +x /usr/local/bin/kind

    - name: Verify kind installation
      command: kind --version
      register: kind_version
      
  when: kind_check.failed
  become: true