- name: Set variables
  set_fact:    
    remote_secret_dir: "remote-secrets"

- name: Ensure remote secrets directory exists
  file:
    path: "{{ remote_secret_dir }}"
    state: directory
    mode: '0755'

- name: Retrieve remote secret for the cluster
  shell: |
    istioctl create-remote-secret \
        --context={{ cluster.kubecontext }} \
        --name={{ cluster.name }} >  {{ remote_secret_dir }}/{{ cluster.name }}.yaml
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"
  register: remote_secret
  changed_when: true

- name: Print saved secret location
  debug:
    msg: "Saved remote secret for cluster {{ cluster.name }} at {{ remote_secret_dir }}/{{ cluster.name }}.yaml"
