- name: Set variables
  set_fact:    
    secret_file: "/remote-secrets/{{ cluster.name }}.yaml"

- name: Retrieve remote secret for the cluster
  shell: |
    istioctl x create-remote-secret --name {{ cluster.name }} \
    --kubeconfig {{ cluster.kubeconfig }} > {{ cluster.secret_file }}
  environment:
    KUBECONFIG: "{{ cluster.kubeconfig }}"
  register: remote_secret
  changed_when: true


- name: Print saved secret location
  debug:
    msg: "Saved remote secret for cluster {{ cluster.name }} at {{ cluster.secret_file }}"