---
- name: Set variables
  set_fact:    
    remote_secret_dir: "remote-secrets"

- name: Get API Server pod IP for cluster {{ source_cluster.name }}
  shell: |
    kubectl --context {{ source_cluster.kubecontext }} get pod -n kube-system -l component=kube-apiserver -o jsonpath='{.items[0].status.podIP}'
  environment:
    KUBECONFIG: "{{ source_cluster.kubeconfig }}"
  register: api_server_ip
  changed_when: false

- name: Get Kubernetes API server port
  command: kubectl --context {{ source_cluster.kubecontext }}  config view --minify -o jsonpath='{.clusters[0].cluster.server}'
  environment:
    KUBECONFIG: "{{ source_cluster.kubeconfig }}"  
  register: api_server_url

- name: Extract API server port
  set_fact: 
    api_server_port: "{{ api_server_url.stdout.split(':')[-1] }}"   

- name: Display API server address and port
  debug:
    msg:
      - "The Kubernetes API server address is: {{ api_server_ip.stdout }}"
      - "The Kubernetes API server port is: {{ api_server_port }}"

- name: Create remote secret for cluster {{ source_cluster.name }} to be applied on {{ target_cluster.name }}
  shell: |
    istioctl create-remote-secret \
      --context {{ source_cluster.kubecontext }} \
      --server=https://{{ api_server_ip.stdout }}:{{ api_server_port }} \
      --name {{ source_cluster.name }}  >  {{ remote_secret_dir }}/{{ source_cluster.name }}.yaml 
  environment:
    KUBECONFIG: "{{ source_cluster.kubeconfig }}"
  when: api_server_ip.stdout is defined and api_server_port is defined
