# app1.yaml (example for app1 Helm chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accountsv2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/multiclusteristio/poc.git
    targetRevision: HEAD
    path: apps/helm/accounts.api.v2
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: accounts 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
