apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: account-mtls
  namespace: accounts
spec:
  host: accounts-ms-base.accounts.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
