apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
 name: account-ap
 namespace: banking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: accounts
      app.kubernetes.io/name: ms-base
  rules:
  - from:
    - source:
        namespaces: ["*"] 
    to:
    - operation:
        paths: ["/api/v1/accounts"]
    when:
    - key: request.auth.claims[sub]
      values: ["masterplan-clientid"]   
    to:
    - operation:
        methods: ["GET"]
        paths: ["/api/v1/accounts"]
    when:
    - key: request.auth.claims[sub]
      values: ["masterplan-clientid", "transfers-clientid"]               
