apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: account-ingress-access
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: accounts
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
