apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: account-ingress-access
  namespace: accounts
spec:
  selector:
    matchLabels:
        app.kubernetes.io/instance: accounts
        app.kubernetes.io/name: ms-base
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/transfers/sa/transfers-ms-base"]
