---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: accounts-dest-rule
  namespace: accounts
spec:
  host: accounts-ms-base.accounts.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10
        maxRequestsPerConnection: 10

    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failover:
          - from: auh-zone
            to: dxb-zone

    outlierDetection:
      consecutive5xxErrors: 1
      interval: 20s
      baseEjectionTime: 30s

