apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
  namespace: accounts
spec:
  hosts:
  - "accounts-ms-base.accounts.svc.cluster.local"
  http:
  - match:
      - uri:
          prefix: /api/v1/ 
    route:
      - destination:
          host: accounts-ms-base.accounts.svc.cluster.local 
        weight: 90
  - match:
      - uri:
          prefix: /api/v2/  
    route:
      - destination:
          host: accounts-ms-base.accounts.svc.cluster.local 
        weight: 10 
