apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/instance: accounts
  name: accounts-internal
  namespace: accounts
spec:
  hosts:
    - 'accounts-ms-base.accounts.svc.cluster.local'
  http:
    - match:
        - uri:
            prefix: /accounts
      rewrite:
        uri: /api
      route:
        - destination:
            host: accounts-ms-base.accounts.svc.cluster.local
            port:
              number: 80     