apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: account
  namespace: accounts
spec:
  hosts:
  - "*" 
  gateways:
  - istio-system/banking
  http:
  - match:
    - uri:
        exact: /api/v1/accounts
    route:
    - destination:
        host: accounts-ms-base.accounts.svc.cluster.local 
        port:
          number: 80
