apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
  namespace: accounts
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/banking 
  http:
  - match:
    - uri:
        exact: /accounts
    route:
    - destination:
        host: accounts-ms-base.accounts.svc.cluster.local
